services:
  autentikasi:
    build:
      context: ./autentikasi
      dockerfile: dockerfile
    volumes:
      - ./autentikasi:/var/www
    ports:
      - "8001:8000"
    command: php artisan serve --host=0.0.0.0 --port=8000
    environment:
      DB_CONNECTION: mysql
      DB_HOST: autentikasi_db
      DB_PORT: 3306
      DB_DATABASE: autentikasi_db
      DB_USERNAME: root
      DB_PASSWORD: root
    depends_on:
      - autentikasi_db
    networks:
      - microservices_net

  autentikasi_db:
    image: mysql:8.4
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: autentikasi_db
    volumes:
      - autentikasi_db_data:/var/lib/mysql
    networks:
      - microservices_net


  ptsp:
    build:
      context: ./ptsp
      dockerfile: dockerfile
    volumes:
      - ./ptsp:/var/www
    ports:
      - "8002:8000"    
    command: php artisan serve --host=0.0.0.0 --port=8000
    environment:
      DB_CONNECTION: mysql
      DB_HOST: ptsp_db
      DB_PORT: 3306
      DB_DATABASE: ptsp_db
      DB_USERNAME: root
      DB_PASSWORD: root
    depends_on:
      - ptsp_db
    networks:
      - microservices_net

  ptsp_db:
    image: mysql:8.4
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ptsp_db
    volumes:
      - ptsp_db_data:/var/lib/mysql
    networks:
      - microservices_net


  # Container untuk tampilan ui php my admin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_HOSTS: autentikasi_db,ptsp_db  
      PMA_USER: root
      PMA_PASSWORD: root
    networks:
      - microservices_net

  nginx:
    build:
      context: ./nginx
      dockerfile: dockerfile
    container_name: nginx-gateway
    ports:
      - "80:80"
    depends_on:
      - ptsp
      - autentikasi
    networks:
      - microservices_net

# Jaringan microservices
networks:
  microservices_net:


# Menyimpan record db dari masing-maasing layanan
volumes:
  autentikasi_db_data:
  ptsp_db_data:
